import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

export default function EpisodeProfile() {
  const router = useRouter();
  const [data, setData] = useState({});

  useEffect(() => {
    router.query.pid &&
      fetch(`https://rickandmortyapi.com/api/episode/${router.query.pid}`)
        .then((res) => res.json())
        // Логика, если эпизоды будут приходить массивом IRI
        .then(async (res) => {
          if (res.characters?.length) {
            await fetch(
              `https://rickandmortyapi.com/api/character/${res.characters
                .map((character) => character.split("/").pop())
                .join(",")}`
            )
              .then((res) => res.json())
              .then((characters) => {
                console.log(characters)
                res.characters = Array.isArray(characters) ? characters : [characters]
              });
          }

          return res;
        })
        .then((res) => setData(res));
  }, [router.query]);

  console.log(data.character);

  return (
    <>
      <Head>
        <title>{data.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ display: "flex", flexDirection: "column", gap: "10px", marginLeft: "50px" }}>
        <button onClick={router.back}>GO BACK</button>
        <h1>{data.name}</h1>
        <div style={{ display: "grid", gridColumn: 2, gap: "10px" }}>
          <div
            style={{ display: "flex", flexDirection: "column", gap: "10px" }}
          >
            <h3>Informations</h3>
            <p>{data.episode}</p>
            <p>{data.air_date}</p>
          </div>
          <div
            style={{ display: "flex", flexDirection: "column", gap: "10px" }}
          >
            <h3>Characters</h3>
            {data?.characters?.map((character) => (
              <Link key={character.id} href={`/characters/${character.id}`}>
                <div>
                    <p>{character.name}</p>
                </div>
              </Link>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
